excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - scripts
  - API.swift

enable_rules:
  - function_default_parameter_at_end

disabled_rules: # rule identifiers to exclude from running
  - large_tuple
  - function_parameter_count
  - trailing_whitespace
  - trailing_comma
  - line_length
  - empty_enum_arguments
  - type_body_length
  - function_body_length
  - file_length
  - cyclomatic_complexity
  - nesting
  - type_name

line_length: 130
maxEmptyLines: 1
